<<<<<<< HEAD
version: "3"
=======
version: '3'
>>>>>>> 82d38eb (Added Integration Tests)

services:
  mysql_cloud:
    image: mysql:latest
    environment:
<<<<<<< HEAD
      MYSQL_ROOT_PASSWORD: "root"
=======
      MYSQL_ROOT_PASSWORD: root
>>>>>>> 82d38eb (Added Integration Tests)
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
<<<<<<< HEAD
<<<<<<< HEAD
    environment:
      CHOKIDAR_USEPOLLING: "true"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "cloud"
      MYSQL_HOST: "mysql_cloud"
    depends_on:
      - mysql_cloud
    volumes:
      - .:/app
    command: ["sh", "-c", "sleep 20 && npm run dev"]
    
=======
    env_file:
      - .env
=======
>>>>>>> 77cbef3 (Fixed ENV for Docker COmpose)
    environment:
      CHOKIDAR_USEPOLLING: "true"
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cloud
      MYSQL_HOST: host.docker.internal
    volumes:
      - .:/app

>>>>>>> 82d38eb (Added Integration Tests)
volumes:
  mysql_data:
