version: '3'

services:
  mysql_cloud:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cloud
      MYSQL_HOST: host.docker.internal
    volumes:
      - .:/app

volumes:
  mysql_data:
