version: '3'

services:
  mysql_cloud:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app

volumes:
  mysql_data:
