logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/error.log
        - /var/log/combined.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    severity-processor:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
          map_values:
            "debug": "DEBUG"
            "info": "INFO"
            "warning": "WARNING"
            "error": "ERROR"
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, severity-processor]

