name: Start NodeJS Server with MySQL
description: Composite action to start a NodeJS server with MySQL
inputs:
  mysql_root_password:
    description: "MySQL Root Password"
    required: true
  mysql_username:
    description: "MySQL Username"
    required: true
  mysql_database:
    description: "MySQL Database Name"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 19
    - name: Creating a .env
      shell: bash
      run: |
        echo "user=${{ inputs.mysql_username }}" > .env
        echo "password=${{ inputs.mysql_root_password }}" >> .env
        echo "host=localhost" >> .env
        echo "database=${{ inputs.mysql_database }}" >> .env
    - name: Set up MySQL
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.0"
        root-password: ${{ inputs.mysql_root_password }}
    - name: Create DATABASES
      shell: bash
      run: |
        mysql -u${{inputs.mysql_username}} -p${{inputs.mysql_root_password}} -e 'CREATE DATABASE ${{inputs.mysql_database}};'
    - name: Starting node server
      shell: bash
      run: |
        npm install
        npm start &
    - name: Calling health endpoint
      shell: bash
      run: |
        curl -vvvv http://localhost:8080/healthz
