name: "Build Image using Packer"
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "19"
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          root-password: "root"
      - name: Create DATABASES
        run: |
          mysql -uroot -proot -e 'CREATE DATABASE cloud;'
          mysql -uroot -proot -e 'SHOW DATABASES;'
      - name: Starting node server
        run: |
          npm install
          npm start &
      - name: Calling heatlh endpoint
        run: |
          curl -vvvv http://localhost:8080/healthz
      - name: Calling Integrations tests
        run: npm run test

  build_image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: "Delete Image if exists"
        continue-on-error: true
        run: |
          gcloud compute images delete "centos-image" --quiet
      - name: Create a zip
        run: |
          tar -czvf webapp.tar.gz . || echo "tar command failed"
          ls -la
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
      - name: Pre Steps of packer
        run: |
          packer init ./packer/main.pkr.hcl
          packer fmt ./packer/main.pkr.hcl
          packer validate ./packer/main.pkr.hcl
      - name: Build Packer
        run: packer build ./packer/main.pkr.hcl
