name: "Build Image using Packer and Continuous Deployment"
# on:
#   push:
#     branches:
#       - main
on: push
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get Code
  #       uses: actions/checkout@v3
  #     - name: Starting a Node Server with MySQL
  #       uses: ./.github/actions/integration_tests
  #       with:
  #         mysql_root_password: ${{secrets.MYSQL_PASSWORD}}
  #         mysql_username: ${{secrets.MYSQL_USERNAME}}
  #         mysql_database: ${{vars.DATABASE_NAME}}
  #         projectId: ${{secrets.PROJECTID}}
  #         gcloud_logging_enabled: ${{vars.GCLOUD_LOGGING_ENABLED}}
  #       env:
  #         DATABASE_NAME: ${{vars.DATABASE_NAME}}
  build_image:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: Create a zip
        run: tar -czvf webapp.tar.gz . || true
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
      - name: Initializing Packer
        run: packer init ./packer/main.pkr.hcl
      - name: Build Packer
        id: packer_build
        run: |
          packer_output=$(packer build -var "project_id=${{ vars.PROJECT_ID }}" -var "ssh_username=${{ vars.SSH_USERNAME }}" -var "zone=${{ vars.ZONE }}" ./packer/main.pkr.hcl)
          image_name=$(echo "$packer_output" | awk -F ': ' 'END {print $NF}')
          echo "Packer output: $packer_output"
          echo "Image Name: $image_name"
          echo "::set-output name=image_name::$image_name"
        env:
          project_id: ${{vars.PROJECT_ID}}
          ssh_username: ${{vars.SSH_USERNAME}}
          zone: ${{vars.ZONE}}
      - name: Print Image ID
        run: |
          echo "Image ID from Packer step: ${{ steps.packer_build.outputs.image_name }}"
      - name: Creating a Instance Template
        run: gcloud compute instance-templates create new-instance-template --source-instance-template=instance-template-vpc20240409214734294400000001 --image=${{ steps.packer_build.outputs.image_name }}
