name: "Packer Check on Pull Request"
on:
  push:
    branches:
      - assignment_4
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
      - name: Packer Commands
        run: |
          packer init ./packer/main.pkr.hcl
          packer fmt ./packer/main.pkr.hcl
          packer validate ./packer/main.pkr.hcl
