name: "Run integration tests"
on:
  push:
    branches:
      - "assignment_3"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Start Docker daemon
        run: sudo service docker start
      - name: Start SQL and NodeJS on Docker
        run: docker-compose up -d
      - name: Check for services
        run: |
          sleep 10
          docker ps
          docker logs webapp_mysql_cloud_1
          docker logs webapp_node_app_1
      - name: CCalling heatlh endpoint
        run: |
          sleep 10
          curl -vvvv http://localhost:8080/healthz
      - name: Stop services
        run: docker-compose down
