name: "Pull Request Merge Check"
on:
  push:
    branches:
      - assignment_3
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "19"
      - name: Install Dependencies
        run: npm install
      - name: Hello World Output
        run: echo "Hello World"
