name: Node.js MySQL Integration Workflow

on:
  workflow_call:
    inputs:
      mysql_root_password:
        description: 'MySQL Root Password'
        required: true
        type: string
      mysql_username:
        description: 'MySQL Username'
        required: true
        type: string
      mysql_database:
        description: 'MySQL Database Name'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 19
      - name: Creating a .env
        run: |
          echo "user=${{ inputs.mysql_username }}" > .env
          echo "password=${{ inputs.mysql_root_password }}" >> .env
          echo "host=localhost" >> .env
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: ${{ inputs.mysql_root_password }}
          mysql database: ${{ inputs.mysql_database }}
      - name: Starting node server
        run: |
          npm install
          npm start &
      - name: Calling health endpoint
        run: |
          curl -vvvv http://localhost:8080/healthz
      - name: Calling Integrations tests
        run: npm run test
